<a href="https://colab.research.google.com/github/king-davi/NumPy-program./blob/main/NumPy_program.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Question 1
# Write a Python program to convert an array to an ordinary list with the same items.
# We can use the np.tolist() function.
import numpy as np
arr = np.array([2, 4, 3])
list = arr.tolist()

print(f'List: {list}')

List: [2, 4, 3]


In [ ]:
# Question 2 
# Write a NumPy program to compute the sum of the diagonal elements of a given array.
# Hint: There are two possible methods to solve this problem: 
# Manually (without direct function). 
# Using the trace function
numpy_array_from_list = np.array([2, 4, 3])
print('original array: ', numpy_array_from_list)
six_plus_original = numpy_array_from_list  + 6
print(six_plus_original)

original array:  [2 4 3]
[ 8 10  9]


In [ ]:
# Question 3
# Given an array of your choice, get all the values higher than X:
# If a = [[1,2],[3,5]] and x = 2 :  then 3 and 5 are higher than 2
a = np.array([[1,2], [3,5]])
x = 2
array = np.greater(a, x)
array

array([[False, False],
       [ True,  True]])

In [ ]:
# Question 4
# Given two arrays, A & B have the same shape. 
# The task is to apply addition by hand: C is the new array. 
a = np.random.rand(2,7)
b = np.random.rand(2,7)
new_array = (a + b)
new_array

array([[1.15681565, 0.61583916, 1.02077699, 1.3004206 , 1.80995405,
        1.00005092, 0.37486193],
       [0.58728756, 1.16132545, 0.29206911, 0.50601114, 1.11855942,
        0.65057899, 1.19328868]])

In [ ]:
# Question 5
# Write a NumPy program to subtract the mean of each row of a given matrix.
# Hint: use the mean function
import numpy as np
arr = np.random.rand(3,6)
x = arr - arr.mean(axis=1, keepdims=True)
x


array([[ 0.55726009, -0.22785977,  0.1908023 , -0.27985256, -0.4191051 ,
         0.17875504],
       [-0.11297917,  0.16293513, -0.28573326,  0.08548653,  0.29380244,
        -0.14351167],
       [-0.04082811,  0.15761015, -0.15690086,  0.35951046, -0.11280841,
        -0.20658323]])

In [ ]:
# What is random.randint
# What is random.rand
# what is the difference between both
What is random.randint?? The randint() method returns an integer number selected element from the specified range.
What is random.rand?? random.rand returns an evenly distributed random real number greater than or equal to 0 and less than 1. 
what is the difference between both?? The diffrience is The random command will generate a rondom value present in a given list/dictionary.
And randint command will generate a random integer value from the given list/dictionary.